from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Patient)
admin.site.register(NextofKin)
admin.site.register(Payment)
admin.site.register(Obstetric_historyformone)
# admin.site.register(Obstetric_historyformtwo)
admin.site.register(Obstetric_historyformthree)
admin.site.register(Obstetric_historyformfour)
admin.site.register(Obstetric_historyformfive)
admin.site.register(Obstetric_historyformsix)
admin.site.register(past_medical_and_surgical_history)
admin.site.register(antenatal_records)
admin.site.register(physical_examination)
admin.site.register(Tetanus_Toxoid)
admin.site.register(TetanusToxoid)
admin.site.register(VitalSigns)
admin.site.register(report_labourone)
admin.site.register(report_labourtwo)
admin.site.register(Report_labourthree)
admin.site.register(after_delivery)
admin.site.register(Vital_Chart)
admin.site.register(Pre_anaesthetic)
admin.site.register(Magnesium_sulphate)
admin.site.register(Pre_operationone)
admin.site.register(Pre_operationtwo)
admin.site.register(Pre_operationthree)
admin.site.register(Pre_operationfour)
admin.site.register(before_anaesthesia)
admin.site.register(before_incision)
admin.site.register(before_leaving_OR)
admin.site.register(anaesthetic_record)
admin.site.register(theatre_operations)
admin.site.register(post_operation)
admin.site.register(impatient_treatment)
admin.site.register(nursing_care_plan)
admin.site.register(discharge)
admin.site.register(cardex)
admin.site.register(disease_codes)
admin.site.register(continuation_sheet)
admin.site.register(charge_sheet)
admin.site.register(gate_pass)
admin.site.register(payment_particulars)
admin.site.register(summary_of_labour)
admin.site.register(fetal_heart_rate)
admin.site.register(dilation)
admin.site.register(four_hourly_temp)
admin.site.register(results_of_operation)
admin.site.register(pulse_BP)
admin.site.register(contractions)
admin.site.register(graph)
admin.site.register(Hour)
admin.site.register(intake)
admin.site.register(output)
admin.site.register(CustomUser)
