# Generated by Django 2.2.12 on 2023-05-31 08:43

from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obstetric_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LMP', models.DateField(max_length=10)),
                ('EDD', models.DateField(max_length=10)),
                ('GRAVID', models.CharField(max_length=30)),
                ('PARITY', models.IntegerField(max_length=10)),
                ('date_of_birth', models.IntegerField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('place_of_birth', models.CharField(max_length=30)),
                ('weight', models.IntegerField(max_length=20)),
                ('duration_of_labour', models.IntegerField(max_length=10)),
                ('Mode_of_delivery', models.CharField(max_length=30)),
                ('pueperium', models.IntegerField(max_length=20)),
                ('complications', models.CharField(max_length=30)),
                ('feeding', models.CharField(max_length=30)),
                ('life_state', models.BooleanField(null=True)),
                ('menarche', models.IntegerField(max_length=20)),
                ('cycle_duration', models.DurationField(max_length=20)),
                ('Duration', models.DurationField(max_length=20)),
                ('regularity', models.CharField(max_length=20)),
                ('flow', models.CharField(max_length=20)),
                ('present_pregnancy', models.CharField(max_length=20)),
                ('date_of_quickening', models.DateField(max_length=10)),
                ('gestation_on_firstvisit', models.IntegerField(max_length=10)),
                ('clinical_estimtion', models.CharField(max_length=100)),
                ('complaints', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('Complaints', models.CharField(max_length=30)),
                ('pain', models.CharField(max_length=30)),
                ('bleeding', models.BooleanField(null=True)),
                ('vomiting', models.BooleanField(null=True)),
                ('frequency', models.IntegerField(max_length=30)),
                ('operations', models.IntegerField(max_length=20)),
                ('blood_transfusion', models.BooleanField(null=True)),
                ('recent_drugs_taken', models.CharField(max_length=30)),
                ('admitting_officer', models.CharField(max_length=30)),
                ('signature', jsignature.fields.JSignatureField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=5)),
                ('maritalstatus', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('educationlevel', models.CharField(max_length=30)),
                ('residence', models.CharField(max_length=30)),
                ('id_number', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='NextofKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Relationship', models.CharField(max_length=10)),
                ('tel_number', models.CharField(max_length=15)),
                ('Residence', models.CharField(max_length=30)),
                ('patient', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
    ]
