# Generated by Django 2.2.12 on 2023-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obstetric_history',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='obstetric_history',
            name='duration',
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='duration_menstrual',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='duration_pregnancy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='cycle_duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='duration_of_labour',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
