# Generated by Django 2.2.12 on 2023-05-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20230531_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obstetric_history',
            old_name='cycle_duration',
            new_name='cycle',
        ),
        migrations.RenameField(
            model_name='obstetric_history',
            old_name='duration_of_labour',
            new_name='length_labour',
        ),
        migrations.RenameField(
            model_name='obstetric_history',
            old_name='duration_menstrual',
            new_name='length_menstrual',
        ),
        migrations.RenameField(
            model_name='obstetric_history',
            old_name='duration_pregnancy',
            new_name='length_pregnancy',
        ),
    ]
