# Generated by Django 2.2.12 on 2023-06-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20230531_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='antenatal_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('rhesus', models.CharField(max_length=10)),
                ('hb', models.FloatField()),
                ('rbs', models.FloatField()),
                ('vdrl', models.BooleanField(default=False)),
                ('serology', models.CharField(max_length=100)),
                ('hep_b', models.BooleanField(default=False)),
                ('urinalysis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('twin', models.BooleanField()),
                ('tb', models.BooleanField()),
                ('essen_hypert', models.BooleanField()),
                ('sample', models.CharField(max_length=100)),
                ('heart_did', models.BooleanField()),
                ('relation', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='past_medical_and_surgical_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(max_length=100)),
                ('tb', models.BooleanField(default=False)),
                ('renal', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('essen_hypert', models.BooleanField(default=False)),
                ('heart', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('treatment', models.TextField(blank=True)),
                ('others', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='physical_examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.IntegerField()),
                ('pulse_rate', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('SPO2', models.IntegerField()),
                ('anaemia', models.BooleanField(default=False)),
                ('oedema', models.BooleanField(default=False)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('urine', models.TextField(blank=True)),
                ('investigations', models.TextField(blank=True)),
                ('fundal_height', models.IntegerField()),
                ('presentation', models.CharField(max_length=100)),
                ('lie', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('engagement', models.BooleanField(default=False)),
                ('spleen', models.BooleanField(default=False)),
                ('liver', models.BooleanField(default=False)),
                ('proteins', models.CharField(max_length=100)),
                ('ext_genitalia', models.CharField(max_length=100)),
                ('vaginal_wall', models.CharField(max_length=100)),
                ('fetal_position', models.CharField(max_length=100)),
                ('consistency', models.CharField(max_length=100)),
                ('dilation', models.FloatField()),
                ('membrane_or_cord_status', models.CharField(max_length=100)),
                ('effacement', models.CharField(max_length=100)),
                ('vaginal_discharge', models.CharField(max_length=100)),
                ('acetone', models.BooleanField(default=False)),
                ('sacral_promontory', models.FloatField()),
                ('sacral_curve', models.FloatField()),
                ('ischial_spines', models.FloatField()),
                ('intrapubic_angle', models.FloatField()),
                ('intratuberous_diameter', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='socal_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.BooleanField(null=True)),
                ('alcohol', models.BooleanField(null=True)),
                ('sports', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='illness',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='others',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='treatment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='PARITY',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='admitting_officer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='date_of_birth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='gestation_on_firstvisit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='menarche',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='operations',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='pueperium',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='recent_drugs_taken',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='antenatal_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('maturity', models.CharField(max_length=100)),
                ('urine_analysis', models.CharField(max_length=100)),
                ('fundal_height', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('presentation', models.CharField(max_length=100)),
                ('pallor', models.BooleanField(default=False)),
                ('lie', models.CharField(max_length=100)),
                ('fetal_heart_rate', models.PositiveIntegerField()),
                ('fetal_movement', models.CharField(max_length=100)),
                ('engagement', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('next_visit', models.DateField()),
                ('family_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.FamilyHistory')),
            ],
        ),
    ]
