# Generated by Django 2.2.12 on 2023-06-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20230602_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='TetanusToxoid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_visit', models.DateField()),
                ('second_visit', models.DateField()),
                ('third_visit', models.DateField()),
                ('fourth_visit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vital_signs', models.DateField()),
                ('temperature_vital_signs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_vital_signs', models.TimeField()),
                ('blood_pressure_vital_signs', models.CharField(max_length=20)),
                ('pulse_vital_signs', models.PositiveIntegerField()),
                ('respiratory_rate', models.PositiveIntegerField()),
                ('name_vital_signs', models.CharField(max_length=100)),
            ],
        ),
    ]
