# Generated by Django 2.2.12 on 2023-06-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_tetanustoxoid_vitalsigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='after_delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_of_the_mother', models.TextField(blank=True)),
                ('condition_of_the_baby', models.TextField(blank=True)),
                ('fundus', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse', models.PositiveIntegerField()),
                ('respiration', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('loss_pv', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('birth_notification_no', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
                ('date_of_notification', models.DateField()),
                ('placenta_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notified', models.BooleanField(default=False)),
                ('abnormalities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='drugs_during_labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('began', models.DateTimeField()),
                ('membranes_ruptured', models.DateTimeField()),
                ('full_dilation', models.DateTimeField()),
                ('baby_born', models.DateTimeField()),
                ('placenta_expelled', models.DateTimeField()),
                ('amount_of_loss', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('hours', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='duration_of_labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_labour', models.DateField()),
                ('time_labour', models.TimeField()),
                ('drug_labour', models.CharField(max_length=100)),
                ('given_by', models.CharField(max_length=100)),
                ('dose_labour', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('perinuem', models.TextField(blank=True)),
                ('satures', models.IntegerField()),
                ('by_when', models.DateField()),
                ('first_satge_duration', models.TimeField()),
                ('second_stage_duration', models.TimeField()),
                ('third_stage_duration', models.TimeField()),
                ('total_time', models.CharField(max_length=100)),
                ('delivered_by', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('midwife', models.CharField(max_length=100)),
                ('student_or_nurse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='report_labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_report_labour', models.DateField()),
                ('report', models.TextField(blank=True)),
            ],
        ),
    ]
