# Generated by Django 2.2.12 on 2023-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_after_delivery_drugs_during_labour_duration_of_labour_report_labour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mgnesium_sulphate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('respiratory_rate', models.PositiveIntegerField()),
                ('urine', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
                ('deep_tendon_reflex', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pre_anaesthetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emergency', models.BooleanField(default=False)),
                ('elective', models.BooleanField(default=False)),
                ('past_history', models.TextField()),
                ('present_condition', models.TextField()),
                ('regular_condition', models.TextField()),
                ('allergies', models.TextField()),
                ('airway_assessment', models.TextField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('heart_sounds', models.TextField()),
                ('pallor', models.BooleanField(default=False)),
                ('edema', models.BooleanField(default=False)),
                ('other', models.TextField()),
                ('operation', models.CharField(max_length=100)),
                ('pupils', models.CharField(max_length=100)),
                ('other_cns', models.TextField()),
                ('asa_class', models.PositiveIntegerField()),
                ('preoperative_instructions', models.TextField()),
                ('anesthetist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSignsObservationChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('pulse', models.PositiveIntegerField()),
                ('respiratory_rate', models.PositiveIntegerField()),
            ],
        ),
    ]
