# Generated by Django 2.2.12 on 2023-06-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_mgnesium_sulphate_pre_anaesthetic_vitalsignsobservationchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('procedure', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('surgeon', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('ward', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('anesthetist', models.CharField(max_length=100)),
                ('time_done', models.DateTimeField()),
                ('bp_pre_op', models.CharField(max_length=20)),
                ('temp_pre_op', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cvp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse_pre_op', models.IntegerField()),
                ('weight_pre_op', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resp_pre_op', models.IntegerField()),
                ('height_pre_op', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fetal_hr', models.IntegerField()),
                ('xray_scan', models.BooleanField()),
                ('ecg', models.FileField(blank=True, upload_to='ecg_files/')),
                ('other_form', models.FileField(blank=True, upload_to='other_forms/')),
                ('bladder_emptied_time', models.DateTimeField()),
                ('urinalysis', models.TextField()),
                ('comments', models.TextField()),
                ('pre_op_visit_done', models.BooleanField()),
                ('or_nurse_name', models.CharField(max_length=100)),
                ('prepared_by', models.CharField(max_length=100)),
                ('handed_over_by', models.CharField(max_length=100)),
                ('time_arrived_reception', models.DateTimeField()),
                ('received_by', models.CharField(max_length=100)),
                ('omplete_consent_form', models.BooleanField()),
                ('complete_anaesthesia_assessment', models.BooleanField()),
                ('blood_result_hb', models.BooleanField(verbose_name='Blood Result: Hb*')),
                ('blood_result_u_and_es', models.BooleanField(verbose_name='Blood Result: U&E’s')),
                ('blood_result_blood_sugar', models.BooleanField(verbose_name='Blood Result: Blood Sugar')),
                ('x_match', models.BooleanField(verbose_name='X-Match')),
                ('medication_pre_medication', models.BooleanField(verbose_name='Medication: Pre-medication')),
                ('medication_regular_medication', models.CharField(max_length=200, verbose_name='Medication: Regular Medication (specify)')),
                ('allergies', models.BooleanField()),
                ('nil_by_mouth_fasted_from', models.DateTimeField(verbose_name='Nil by mouth: fasted from')),
                ('contact_lens_removed', models.BooleanField()),
                ('hearing_aid_limb_removed', models.BooleanField()),
                ('implants_prosthetics', models.BooleanField()),
                ('dental_caps_crowns_bridge_work_present', models.BooleanField()),
                ('dentures_removed_loose_teeth', models.BooleanField()),
                ('jewellery_valuables_removed', models.BooleanField()),
                ('makeup_nail_vanish_removed', models.BooleanField()),
                ('bath_shower_going_on', models.BooleanField(verbose_name='Bath/Shower/Going On')),
                ('shave_skin_preparation', models.BooleanField(verbose_name='Shave/Skin Preparation')),
                ('surgical_site_marked', models.BooleanField(verbose_name='Surgical Site Marked')),
            ],
        ),
    ]
