# Generated by Django 2.2.12 on 2023-06-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_pre_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='before_anaesthesia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_confirm_identity', models.BooleanField(null=True)),
                ('site_marked', models.BooleanField(null=True)),
                ('anesthesia_check_complete', models.BooleanField(null=True)),
                ('pulse_oximeter_on_patient', models.BooleanField(null=True)),
                ('known_allergy', models.BooleanField(null=True)),
                ('difficult_airway_aspiration_risk', models.CharField(max_length=100)),
                ('blood_loss_risk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='before_incision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_introduced', models.BooleanField(default=False)),
                ('patient_info_confirmed', models.BooleanField(default=False)),
                ('antibiotics_given', models.BooleanField(default=False)),
                ('critical_events', models.CharField(blank=True, max_length=200)),
                ('anticipated_blood_loss', models.CharField(blank=True, max_length=100)),
                ('critical_steps', models.TextField(blank=True)),
                ('case_duration', models.CharField(blank=True, max_length=50)),
                ('concerns_to_anaesthetist', models.TextField(blank=True)),
                ('concerns_to_nursing_team', models.BooleanField(default=False)),
                ('sterility_confirmed', models.BooleanField(default=False)),
                ('equipment_issues', models.BooleanField(default=False)),
                ('essential_imaging_displayed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='before_leaving_OR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_introduced', models.BooleanField(default=False)),
                ('patient_info_confirmed', models.BooleanField(default=False)),
                ('antibiotics_given', models.BooleanField(default=False)),
                ('nurse_verbal_confirmation', models.CharField(blank=True, max_length=200)),
                ('procedure_name', models.CharField(blank=True, max_length=100)),
                ('instrument_count_completed', models.BooleanField(default=False)),
                ('equipment_issues', models.BooleanField(default=False)),
                ('recovery_concerns', models.TextField(blank=True)),
            ],
        ),
    ]
