# Generated by Django 2.2.12 on 2023-06-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_before_anaesthesia_before_incision_before_leaving_or'),
    ]

    operations = [
        migrations.CreateModel(
            name='anaesthic_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_number', models.CharField(blank=True, max_length=20)),
                ('operation_name', models.CharField(blank=True, max_length=100)),
                ('anaesthetists', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('surgeons', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('premedication_type', models.CharField(blank=True, max_length=100)),
                ('premedication_time_given', models.CharField(blank=True, max_length=50)),
                ('premedication_effects', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('airway_oro_nasopharyngeal_rl_blind', models.BooleanField(default=False)),
                ('airway_oro_nasotracheal_cuff_pack', models.BooleanField(default=False)),
                ('airway_endobronchial_rl_undermask', models.BooleanField(default=False)),
                ('ifi_hand_rl', models.BooleanField(default=False)),
                ('ifi_arm_rl', models.BooleanField(default=False)),
                ('ifi_leg_rl', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='post_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_band', models.BooleanField(default=False)),
                ('inpatient_number', models.CharField(blank=True, max_length=20)),
                ('state_of_consciousness', models.CharField(blank=True, max_length=100)),
                ('indication', models.CharField(blank=True, max_length=100)),
                ('post_operation_class', models.CharField(blank=True, max_length=100)),
                ('the_file', models.CharField(max_length=100)),
                ('bleeding_at_incision', models.CharField(max_length=100)),
                ('bleeding_per_vagina', models.CharField(max_length=100)),
                ('contraction', models.CharField(max_length=100)),
                ('infusions_or_transfusions', models.CharField(max_length=100)),
                ('urine_output_catheter', models.CharField(max_length=100)),
                ('temp_post_operation', models.IntegerField()),
                ('resprate_post_operation', models.IntegerField()),
                ('pulse_post_opeartion', models.IntegerField()),
                ('bp_post_operation', models.IntegerField()),
                ('baby_name', models.IntegerField()),
                ('baby_sex', models.IntegerField()),
                ('baby_bwt', models.IntegerField()),
                ('baby_ip_number', models.IntegerField()),
                ('baby_as', models.IntegerField()),
                ('baby_outcome', models.CharField(max_length=100)),
                ('mother_outcome', models.CharField(max_length=100)),
                ('recording_file', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='theatre_operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('operation_diagnosis', models.CharField(blank=True, max_length=100)),
                ('surgeon', models.CharField(blank=True, max_length=100)),
                ('assistant_surgeons', models.CharField(blank=True, max_length=200)),
                ('scrub_nurse', models.CharField(blank=True, max_length=100)),
                ('anaesthetist', models.CharField(blank=True, max_length=100)),
                ('anesthesia_type', models.CharField(blank=True, max_length=100)),
                ('incisions', models.TextField(blank=True)),
                ('operation_procedure', models.TextField(blank=True)),
            ],
        ),
    ]
