# Generated by Django 2.2.12 on 2023-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20230605_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tetanus_Toxoid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetanus_toxoid_1_before', models.DateField()),
                ('tetanus_toxoid_2_before', models.DateField()),
                ('tetanus_toxoid_3_before', models.DateField()),
                ('tetanus_toxoid_4_before', models.DateField()),
                ('tetanus_toxoid_5_before', models.DateField()),
                ('tetanus_toxoid_1_after', models.DateField()),
                ('tetanus_toxoid_2_after', models.DateField()),
                ('tetanus_toxoid_3_after', models.DateField()),
                ('tetanus_toxoid_4_after', models.DateField()),
                ('tetanus_toxoid_5_after', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Mgnesium_sulphate',
            new_name='Magnesium_sulphate',
        ),
    ]
