# Generated by Django 2.2.12 on 2023-06-06 14:54

from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20230605_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_operationfour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_consent_form', models.BooleanField()),
                ('complete_anaesthesia_assessment', models.BooleanField()),
                ('blood_result_hb', models.BooleanField(verbose_name='Blood Result: Hb*')),
                ('blood_result_u_and_es', models.BooleanField(verbose_name='Blood Result: U&E’s')),
                ('blood_result_blood_sugar', models.BooleanField(verbose_name='Blood Result: Blood Sugar')),
                ('x_match', models.BooleanField(verbose_name='X-Match')),
                ('medication_pre_medication', models.BooleanField(verbose_name='Medication: Pre-medication')),
                ('medication_regular_medication', models.CharField(max_length=200, null=True, verbose_name='Medication: Regular Medication (specify)')),
                ('allergies', models.BooleanField(null=True)),
                ('nil_by_mouth_fasted_from', models.DateTimeField(verbose_name='Nil by mouth: fasted from')),
                ('contact_lens_removed', models.BooleanField(null=True)),
                ('hearing_aid_limb_removed', models.BooleanField(null=True)),
                ('implants_prosthetics', models.BooleanField(null=True)),
                ('dental_caps_crowns_bridge_work_present', models.BooleanField(null=True)),
                ('dentures_removed_loose_teeth', models.BooleanField(null=True)),
                ('jewellery_valuables_removed', models.BooleanField(null=True)),
                ('makeup_nail_vanish_removed', models.BooleanField(null=True)),
                ('bath_shower_going_on', models.BooleanField(null=True, verbose_name='Bath/Shower/Going On')),
                ('shave_skin_preparation', models.BooleanField(null=True, verbose_name='Shave/Skin Preparation')),
                ('surgical_site_marked', models.BooleanField(null=True, verbose_name='Surgical Site Marked')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_operationone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, null=True)),
                ('procedure', models.CharField(max_length=100, null=True)),
                ('reg_no', models.CharField(max_length=100, null=True)),
                ('surgeon', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('ward', models.CharField(max_length=100, null=True)),
                ('doctor', models.CharField(max_length=100, null=True)),
                ('dept', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('anesthetist', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pre_operationthree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_op_visit_done', models.BooleanField()),
                ('or_nurse_name', models.CharField(max_length=100, null=True)),
                ('sign', jsignature.fields.JSignatureField()),
                ('prepared_by', models.CharField(max_length=100, null=True)),
                ('handed_over_by', models.CharField(max_length=100, null=True)),
                ('time_arrived_reception', models.DateTimeField()),
                ('received_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pre_operationtwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_done', models.DateTimeField()),
                ('bp_pre_op', models.CharField(max_length=20, null=True)),
                ('temp_pre_op', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cvp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse_pre_op', models.IntegerField(null=True)),
                ('weight_pre_op', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resp_pre_op', models.IntegerField()),
                ('height_pre_op', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fetal_hr', models.IntegerField(null=True)),
                ('xray_scan', models.BooleanField(null=True)),
                ('ecg', models.FileField(blank=True, upload_to='ecg_files/')),
                ('other_form', models.FileField(blank=True, upload_to='other_forms/')),
                ('bladder_emptied_time', models.DateTimeField()),
                ('urinalysis', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='report_labourone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_report_labour', models.DateField()),
                ('report', models.TextField(blank=True)),
                ('began', models.DateTimeField()),
                ('membranes_ruptured', models.DateTimeField()),
                ('full_dilation', models.DateTimeField()),
                ('baby_born', models.DateTimeField()),
                ('placenta_expelled', models.DateTimeField()),
                ('amount_of_loss', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('hours', models.PositiveIntegerField()),
                ('date_labour', models.DateField()),
                ('time_labour', models.TimeField()),
                ('drug_labour', models.CharField(max_length=100, null=True)),
                ('given_by', models.CharField(max_length=100, null=True)),
                ('dose_labour', models.IntegerField(null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report_labourthree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_stage_duration', models.TimeField()),
                ('second_stage_duration', models.TimeField()),
                ('third_stage_duration', models.TimeField()),
                ('total_time', models.CharField(max_length=100, null=True)),
                ('delivered_by', models.CharField(max_length=100, null=True)),
                ('doctor', models.CharField(max_length=100, null=True)),
                ('midwife', models.CharField(max_length=100, null=True)),
                ('student_or_nurse', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='report_labourtwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perinuem', models.TextField(blank=True)),
                ('satures', models.IntegerField(null=True)),
                ('by_when', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vital_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ip_number', models.CharField(max_length=20, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('pulse', models.PositiveIntegerField()),
                ('respiratory_rate', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='antenatal_profile',
        ),
        migrations.DeleteModel(
            name='drugs_during_labour',
        ),
        migrations.DeleteModel(
            name='duration_of_labour',
        ),
        migrations.DeleteModel(
            name='Pre_operation',
        ),
        migrations.DeleteModel(
            name='report_labour',
        ),
        migrations.DeleteModel(
            name='socal_history',
        ),
        migrations.DeleteModel(
            name='VitalSignsObservationChart',
        ),
        migrations.RenameField(
            model_name='antenatal_records',
            old_name='date',
            new_name='date_records',
        ),
        migrations.RenameField(
            model_name='antenatal_records',
            old_name='pallor',
            new_name='palor',
        ),
        migrations.RemoveField(
            model_name='antenatal_records',
            name='weight',
        ),
        migrations.AddField(
            model_name='antenatal_records',
            name='sign',
            field=jsignature.fields.JSignatureField(null=True),
        ),
        migrations.AddField(
            model_name='antenatal_records',
            name='weight_records',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='four_hourly_temp',
            name='blood_pressure_x_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='four_hourly_temp',
            name='temperature_y_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='alcohol',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='blood_group',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='clinics_attended',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='condition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='essen_hypert',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='hb',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='heart_did',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='hep_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='number_of_visits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='rbs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='relation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='rhesus',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='sample',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='serology',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='smoking',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='sports',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='tb',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='twin',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='urinalysis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obstetric_history',
            name='vdrl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pre_anaesthetic',
            name='anesthetist_sign',
            field=jsignature.fields.JSignatureField(null=True),
        ),
        migrations.AddField(
            model_name='pre_anaesthetic',
            name='glascow_coma_scale',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pre_anaesthetic',
            name='investigations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pre_anaesthetic',
            name='respiratory_system',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='results_of_operation',
            name='operation_x_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='results_of_operation',
            name='operation_y_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='after_delivery',
            name='birth_notification_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='after_delivery',
            name='blood_pressure',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='after_delivery',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anaesthic_record',
            name='anaesthetists',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anaesthic_record',
            name='ip_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anaesthic_record',
            name='operation_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anaesthic_record',
            name='premedication_effects',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anaesthic_record',
            name='premedication_time_given',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anaesthic_record',
            name='premedication_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='antenatal_records',
            name='blood_pressure',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='antenatal_records',
            name='family_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Obstetric_history'),
        ),
        migrations.AlterField(
            model_name='antenatal_records',
            name='fetal_movement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='antenatal_records',
            name='fundal_height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='antenatal_records',
            name='lie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='antenatal_records',
            name='maturity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='antenatal_records',
            name='presentation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='antenatal_records',
            name='urine_analysis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='before_anaesthesia',
            name='blood_loss_risk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='before_anaesthesia',
            name='difficult_airway_aspiration_risk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='before_incision',
            name='anticipated_blood_loss',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='before_incision',
            name='case_duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='before_incision',
            name='critical_events',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='before_leaving_or',
            name='nurse_verbal_confirmation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='before_leaving_or',
            name='procedure_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charge_sheet',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charge_sheet',
            name='charge_done_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='charge_sheet',
            name='service_offered',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contractions',
            name='contractions_gravida',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contractions',
            name='contractions_hospital_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contractions',
            name='contractions_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contractions',
            name='contractions_para',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contractions',
            name='contractions_ruptured_membranes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contractions',
            name='contractions_x_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contractions',
            name='contractions_y_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dilation',
            name='dilation_gravida',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dilation',
            name='dilation_hospital_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dilation',
            name='dilation_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dilation',
            name='dilation_para',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dilation',
            name='dilation_ruptured_membranes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dilation',
            name='dilation_x_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dilation',
            name='dilation_y_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='AS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='DOA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='DOD',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='EL_C_S',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='EM_C_S',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='HPT_management',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='IP_NO',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='SVD',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='acitve_labour',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='birth_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='bleeding',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='bleeding_management',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='complications',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='discharge_meds',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='discharge_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='infections',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='latent_labour',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='mast_insertion_stitch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='normal_delivery_post_SUD',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='others',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='outcome_dead',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='outcome_stable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='pressure_PET_eclampsia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='skilled_normal_delivery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='surgical_delivery_post_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disease_codes',
            name='codes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fetal_heart_rate',
            name='fetal_gravida',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fetal_heart_rate',
            name='fetal_hospital_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fetal_heart_rate',
            name='fetal_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fetal_heart_rate',
            name='fetal_para',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fetal_heart_rate',
            name='fetal_ruptured_membranes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fetal_heart_rate',
            name='fetal_x_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fetal_heart_rate',
            name='fetal_y_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gate_pass',
            name='NHIF_waived',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gate_pass',
            name='Receipt_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gate_pass',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gate_pass',
            name='diagnosis_on_admission',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gate_pass',
            name='diagnosis_on_discharge',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='x_axis_input',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='y_axis_input',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='FR_DU',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='consultant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='dose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='drug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='impatient_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='impatient_ip_NO',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='impatient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='impatient_sex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='impatient_ward',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='prescription_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impatient_treatment',
            name='route',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='magnesium_sulphate',
            name='blood_pressure',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='magnesium_sulphate',
            name='deep_tendon_reflex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='magnesium_sulphate',
            name='output',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='magnesium_sulphate',
            name='urine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='First_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='Last_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='Relationship',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='Residence',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='tel_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='nursing_care_plan',
            name='nursing_DOA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nursing_care_plan',
            name='nursing_IP_NO',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nursing_care_plan',
            name='nursing_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nursing_care_plan',
            name='nursing_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='Complaints',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='GRAVID',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='Mode_of_delivery',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='PARITY',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='clinical_estimtion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='complaints',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='complications',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='cycle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='date_of_birth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='feeding',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='flow',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='gestation_on_firstvisit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='menarche',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='operations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='pain',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='place_of_birth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='present_pregnancy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='pueperium',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='regularity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='educationlevel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='maritalstatus',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='religion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment_particulars',
            name='Cash_NHIF',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment_particulars',
            name='admission_diagnosis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment_particulars',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment_particulars',
            name='discharge_diagnosis',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment_particulars',
            name='waiver_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='SPO2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='bp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='consistency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='dilation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='effacement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='ext_genitalia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='fetal_position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='fundal_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='intrapubic_angle',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='intratuberous_diameter',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='ischial_spines',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='lie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='membrane_or_cord_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='presentation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='proteins',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='pulse_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='respiratory_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='sacral_curve',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='sacral_promontory',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='vaginal_discharge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='vaginal_wall',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='volume',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_examination',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='baby_as',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='baby_bwt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='baby_ip_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='baby_name',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='baby_outcome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='baby_sex',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='bleeding_at_incision',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='bleeding_per_vagina',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='bp_post_operation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='contraction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='indication',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='infusions_or_transfusions',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='inpatient_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='mother_outcome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='post_operation_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='pulse_post_opeartion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='recording_file',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='resprate_post_operation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='state_of_consciousness',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='temp_post_operation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='the_file',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_operation',
            name='urine_output_catheter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pre_anaesthetic',
            name='anesthetist_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pre_anaesthetic',
            name='operation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pre_anaesthetic',
            name='pupils',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pulse_bp',
            name='pulse_BP_gravida',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pulse_bp',
            name='pulse_BP_hospital_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pulse_bp',
            name='pulse_BP_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pulse_bp',
            name='pulse_BP_para',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pulse_bp',
            name='pulse_BP_ruptured_membranes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pulse_bp',
            name='pulse_BP_x_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pulse_bp',
            name='pulse_BP_y_axis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='HC',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='abnormal_placenta_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='baby_apgar_score',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='baby_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='baby_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='blood_loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='drugs_given',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='induction_of_labour',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='labour_delivery',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='length_of_labour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='membranes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='mode_of_delivery',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='mother_Bp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='mother_pulse',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='mother_resp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='number_of_VE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='perineal_repair',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='placenta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='resuscitation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summary_of_labour',
            name='uteranoic_drugs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theatre_operations',
            name='anaesthetist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theatre_operations',
            name='anesthesia_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theatre_operations',
            name='assistant_surgeons',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theatre_operations',
            name='operation_diagnosis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theatre_operations',
            name='scrub_nurse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theatre_operations',
            name='surgeon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_pressure_vital_signs',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='name_vital_signs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='FamilyHistory',
        ),
    ]
