# Generated by Django 2.2.12 on 2023-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_hour_intake_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_number',
            field=models.IntegerField(null=True),
        ),
    ]
