# Generated by Django 4.2.2 on 2023-06-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_alter_after_delivery_id_alter_anaesthetic_record_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obstetric_history',
            old_name='tb',
            new_name='TB',
        ),
        migrations.RenameField(
            model_name='obstetric_history',
            old_name='clinical_estimtion',
            new_name='clinical_estimation',
        ),
    ]
