# Generated by Django 4.2.2 on 2023-06-19 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_remove_payment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient'),
        ),
    ]
