# Generated by Django 4.2.2 on 2023-06-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_remove_payment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='other_payment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.BooleanField(null=True),
        ),
    ]
