# Generated by Django 4.2.2 on 2023-06-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_remove_payment_other_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_type',
            new_name='payment_typ',
        ),
    ]
