# Generated by Django 4.2.2 on 2023-06-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_rename_payment_type_payment_payment_typ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_typ',
            new_name='payment_type',
        ),
    ]
