# Generated by Django 4.2.2 on 2023-06-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_rename_payment_typ_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.BooleanField(max_length=50, null=True),
        ),
    ]
