# Generated by Django 4.2.2 on 2023-06-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.BooleanField(null=True),
        ),
    ]
