# Generated by Django 4.2.2 on 2023-06-21 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0033_remove_payment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstetric_history',
            name='PARITY',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
