# Generated by Django 4.2.2 on 2023-06-21 07:37

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_alter_obstetric_history_parity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstetric_history',
            name='EDD',
            field=models.DateField(null=True, validators=[patients.models.edddate_validator]),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='GRAVID',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='obstetric_history',
            name='LMP',
            field=models.DateField(null=True, validators=[patients.models.lmpdate_validator]),
        ),
    ]
