# Generated by Django 4.2.2 on 2023-06-21 07:44

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_alter_obstetric_history_date_of_quickening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstetric_history',
            name='signature',
            field=jsignature.fields.JSignatureField(null=True),
        ),
    ]
