# Generated by Django 4.2.2 on 2023-06-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0039_rename_date_anaesthetic_record_record_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstetric_history',
            name='history_date',
            field=models.DateField(null=True),
        ),
    ]
