# Generated by Django 4.2.2 on 2023-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0040_alter_obstetric_history_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstetric_history',
            name='GRAVID',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')], default=False),
        ),
    ]
