# Generated by Django 4.2.2 on 2023-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0041_alter_obstetric_history_gravid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstetric_history',
            name='GRAVID',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default=False),
        ),
    ]
