# Generated by Django 4.2.2 on 2023-06-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0045_alter_obstetric_historyformone_gravid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstetric_historyformone',
            name='GRAVID',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
    ]
